### PR TITLE
More packaging fixes

### PR DESCRIPTION
**Pull request by jgleissner**
Hey @adrianschroeter , couple more fixes, sorry. The previous version worked per se but installing the implementation into a subdir in `/usr/lib/build/obsgendiff.d` didn't go so well because the build script tries to execute the directory which causes the build to abort. I've changed it into a single script file to avoid this.

Also includes a small fix for a regex that wasn't quite right and adds a missing runtime dependency.

### CODE REVIEW

**Comment by jgleissner** [comment]
Hi @adrianschroeter , I've snuck another fix in (version changes capture was missing), hope that's fine. Just don't take the branch name literally. ;)

**Comment by jgleissner** [comment]
@adrianschroeter If there are no objections, I'd go ahead and merge this.

**Comment by dirkmueller** [comment]
> @adrianschroeter If there are no objections, I'd go ahead and merge this.

He's on fto for the next weeks

**Comment by jgleissner** [comment]
Thank @dirkmueller for letting me know. I'm gonna go and merge as we need a new package of this rather urgently. I'll deal with potential complaints later.

**Pull request merged**
